#!/usr/bin/env python3
"""
Read all 13 claudepix JSON files and emit a C snippet for direct injection
into clawd_meter.ino (replaces the old 4-animation sprite block).

Usage:
    python3 gen_sprites.py > sprite_block.c   # inspect output
    python3 gen_sprites.py --inject            # patch clawd_meter.ino in-place
"""

import json, re, sys
from pathlib import Path

DATA_DIR = Path(__file__).parent / "claudepix_data"
INO_PATH = Path(__file__).parent.parent / "clawd_meter" / "clawd_meter.ino"

# Ordered list of animation filenames → index 0..12
ANIM_FILES = [
    "idle_breathe",        # 0
    "idle_blink",          # 1
    "idle_look_around",    # 2
    "expression_wink",     # 3
    "expression_surprise", # 4
    "expression_sleep",    # 5
    "dance_bounce",        # 6
    "dance_sway",          # 7
    "work_coding",         # 8
    "work_think",          # 9
    "dance_bounce_dj",     # 10
    "dance_sway_dj",       # 11
    "dance_djmix",         # 12
]

# Rate group → list of animation indices
RATE_GROUPS = [
    [0, 1, 2],       # 0 idle:   idle_breathe, idle_blink, idle_look_around
    [3, 4, 9],       # 1 normal: expression_wink, expression_surprise, work_think
    [5, 7, 8],       # 2 active: expression_sleep, dance_sway, work_coding
    [6, 10, 11, 12], # 3 heavy:  dance_bounce, dance_bounce_dj, dance_sway_dj, dance_djmix
]


def hex_to_rgb565(hexstr: str) -> int:
    h = hexstr.lstrip("#")
    if len(h) == 3:  # expand shorthand #rgb → #rrggbb
        h = h[0]*2 + h[1]*2 + h[2]*2
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def load_anim(filename: str) -> dict:
    path = DATA_DIR / f"{filename}.json"
    with open(path) as f:
        return json.load(f)


def emit_sprite_block() -> str:
    lines = []
    w = lines.append

    w("// ── Sprite data (auto-generated by tools/gen_sprites.py) ────────────")
    w("#define SPRITE_CELL 12")
    w("#define SPRITE_GRID 20")
    w("")

    anims = []
    for filename in ANIM_FILES:
        d = load_anim(filename)
        name = filename  # use filename as C identifier base
        frames = d["frames"]
        palette = d["palette"]  # palette[0] = 'transparent'
        n = len(frames)

        # Build RGB565 palette array; index 0 → 0x0000 (transparent = black bg)
        pal565 = []
        for entry in palette:
            if entry.lower() in ("transparent", ""):
                pal565.append(0x0000)
            else:
                pal565.append(hex_to_rgb565(entry))

        # Emit palette
        pal_vals = ",".join(f"0x{v:04X}" for v in pal565)
        w(f"static const uint16_t PROGMEM {name}_pal[{len(pal565)}] = {{{pal_vals}}};")

        # Emit frame arrays
        for i, frm in enumerate(frames):
            grid = frm["grid"]
            flat = [grid[r][c] for r in range(20) for c in range(20)]
            vals = ",".join(str(v) for v in flat)
            w(f"static const uint8_t PROGMEM {name}_f{i}[400] = {{{vals}}};")

        # Emit holds array
        holds = ",".join(str(frm["hold"]) for frm in frames)
        w(f"static const uint16_t PROGMEM {name}_holds[{n}] = {{{holds}}};")

        # Emit frames pointer array
        w(f"static const uint8_t* const {name}_frames[{n}] = {{")
        for i in range(n):
            w(f"  {name}_f{i},")
        w("};")
        w(f"#define {name.upper()}_NFRAMES {n}")
        w(f"#define {name.upper()}_NPAL   {len(pal565)}")
        w("")

        anims.append((name, n, len(pal565)))

    # Struct definition
    w("struct SpriteAnim {")
    w("  const uint8_t* const* frames;")
    w("  const uint16_t*       holds;")
    w("  const uint16_t*       palette;")
    w("  uint8_t               nframes;")
    w("  uint8_t               npal;")
    w("};")
    w("")

    # ALL_ANIMS[13]
    w("static const SpriteAnim ALL_ANIMS[13] = {")
    for name, n, npal in anims:
        uname = name.upper()
        w(f"  {{ {name}_frames, {name}_holds, {name}_pal, {uname}_NFRAMES, {uname}_NPAL }},")
    w("};")
    w("")

    # Rate group arrays
    for gi, indices in enumerate(RATE_GROUPS):
        vals = ",".join(str(i) for i in indices)
        w(f"static const uint8_t RATE_GROUP_{gi}[] = {{{vals}}};")
        w(f"#define RATE_GROUP_{gi}_LEN {len(indices)}")
    w("")
    w("static const uint8_t* const RATE_GROUP_INDICES[] = {")
    for gi in range(len(RATE_GROUPS)):
        w(f"  RATE_GROUP_{gi},")
    w("};")
    w("static const uint8_t RATE_GROUP_LENS[] = {")
    lens = ",".join(str(len(g)) for g in RATE_GROUPS)
    w(f"  {lens}")
    w("};")

    return "\n".join(lines)


INJECT_START = "// ── Sprite data (auto-generated by tools/gen_sprites.py) ────────────"
INJECT_END   = "// ── Pins ──────────────────────────────────────────────────────"


def inject(block: str) -> None:
    src = INO_PATH.read_text()

    # Find boundaries
    start_idx = src.find("// ── Sprite data")
    end_idx   = src.find("// ── Pins")
    if start_idx == -1 or end_idx == -1:
        print("ERROR: could not find injection markers in clawd_meter.ino", file=sys.stderr)
        sys.exit(1)

    new_src = src[:start_idx] + block + "\n\n" + src[end_idx:]
    INO_PATH.write_text(new_src)
    print(f"Injected {len(block)} bytes into {INO_PATH}", file=sys.stderr)


if __name__ == "__main__":
    block = emit_sprite_block()
    if "--inject" in sys.argv:
        inject(block)
    else:
        print(block)
